### ISSUE TITLE
Scary default settings in docker-compose

### ISSUE THREAD

**Issue by Leopere** [tellform/docker_files#12]
There are very few excusable reasons to publish a Redis server on the internet.

There are even fewer reasons to publish an unconfigured Redis server on the internet.  Why does this example come with defaults like this?  

I can't imagine a use case where you give the public access to an insecure Redis server.  Please let's fix this.

**Comment by whitef0x0** [comment]
@Leopere no there is no reason. We would gladly accept any PRs

**Comment by Leopere** [comment]
I will see what I can do this week is there any guidelines I should look at
or just make a PR and see what happens?

**Comment by Leopere** [comment]
Also, don't mistake my urgency as trying to be a grump I just wanted to try out this tool and saw that the defaults could be a really bad default setting which can contribute to the growing DDoS threat on the internet by getting put on the wall of shame over at https://shodan.io

**Comment by Leopere** [comment]
Hopefully, the PR helps, I may be completely ignoring something somewhere but I followed the README.md and ended up at the conclusion it was copy paste and runnable which it's obvious that's not the path to take.  Next PR I could submit might address documentation linkages if @whitef0x0 has links to documentation that I might be missing and that the project contributors/owners would like to be linked.
