### ISSUE TITLE
Would you be willing to let me add this stuff to the main repo for auto builds on hub.docker.com?

### ISSUE THREAD

**Issue by Leopere** [tellform/docker_files#14]
I just really want to have this to play with I think you've clearly done the best job out of anyone who is doing this.  There's even some guy trying to raise money in your gitter.im for his own GoLang fork that he did no work on if anything that money should be yours because it's already available here.  I'm not sure how to speed things up but I really want to put this on my dev box and have a play.

**Comment by whitef0x0** [comment]
@Leopere Yea I'd be down

**Comment by whitef0x0** [comment]
@Leopere I can give you access to add to this repo if you want

**Comment by Leopere** [comment]
My availability has drastically changed since posting this but I definitely will need a pastime once things settle in hopefully in a week or two.

**Comment by Leopere** [comment]
Definitely still interested in getting it running but going to close this.
